# Generated by Django 3.2.9 on 2021-11-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smthfortest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
